import React from "react";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Link from "next/link";
import { result } from "@types";

interface propsTypes {
  res: result[];
}

const Cats = (props: propsTypes) => {
  const { res } = props;
  console.log("resres", res);
  return (
    <div className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {res.map((item: result) => {
        return (
          <Link href={`/cats/${item.id}`} key={item.id}>
            <div style={{ padding: 50 }}>
              <Image src={item.url} alt="" height={500} width={600} />
            </div>
          </Link>
        );
      })}
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch(
    "https://api.thecatapi.com/v1/images/search?format=json&limit=25"
  );
  const result = await res.json();
  return { props: { res: result } };
};

export default Cats;
