const actionTypes={
    FETCH_POST_DATA :'FETCH_POST_DATA',
    FETCH_POST_DATA_SUCCESS:'FETCH_POST_DATA_SUCCESS',
    FETCH_POST_DATA_FAIL :'FETCH_POST_DATA_FAIL',

    SAVE_FETCHED_DATA:'SAVE_FETCHED_DATA',
};
export default actionTypes;